name: Detect New and Changed CSV Files

on:
  push:
    branches:
      - main # Or your main branch name
    paths:
      - 'data/**' # Watch for changes in the data directory

jobs:
  check-csv-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          format: space-delimited
          files: 'data/*.csv'

      - name: Check for new and changed CSV files
        id: check-changes
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"

          NEW_FILES=$(echo "$CHANGED_FILES" | grep -oE '^A\s+data/.*\.csv$' | wc -l)
          MODIFIED_FILES=$(echo "$CHANGED_FILES" | grep -oE '^M\s+data/.*\.csv$' | wc -l) # M for modified

          if [[ $NEW_FILES -gt 0 ]]; then
            echo "::set-output name=new_csv_found::true"
            echo "New CSV files detected:"
            echo "$CHANGED_FILES" | grep -oE '^A\s+data/.*\.csv$' | cut -d' ' -f2
          else
            echo "::set-output name=new_csv_found::false"
          fi

          if [[ $MODIFIED_FILES -gt 0 ]]; then
            echo "::set-output name=modified_csv_found::true"
            echo "Modified CSV files detected:"
            echo "$CHANGED_FILES" | grep -oE '^M\s+data/.*\.csv$' | cut -d' ' -f2
          else
            echo "::set-output name=modified_csv_found::false"
          fi

      - name: Take action on new files (example)
        if: steps.check-changes.outputs.new_csv_found == 'true'
        run: |
          echo "Performing actions on NEW CSV files..."
          NEW_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -oE '^A\s+data/.*\.csv$' | cut -d' ' -f2)
          for file in $NEW_FILES; do
            echo "Processing new file: $file"
            # Your commands to process each NEW file here
          done

      - name: Take action on modified files (example)
        if: steps.check-changes.outputs.modified_csv_found == 'true'
        run: |
          echo "Performing actions on MODIFIED CSV files..."
          MODIFIED_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -oE '^M\s+data/.*\.csv$' | cut -d' ' -f2)
          for file in $MODIFIED_FILES; do
            echo "Processing modified file: $file"
            # Your commands to process each MODIFIED file here
          done